"""create_table_payments

Revision ID: 68bef59bad4d
Revises: 
Create Date: 2026-02-15 12:32:17.269810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68bef59bad4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_payments',
    sa.Column('cod_payment_id', sa.String(), nullable=False),
    sa.Column('cod_idempotency_key', sa.String(), nullable=False),
    sa.Column('cod_customer_id', sa.String(), nullable=False),
    sa.Column('txt_customer_name', sa.String(), nullable=False),
    sa.Column('txt_customer_document', sa.String(), nullable=False),
    sa.Column('txt_customer_email', sa.String(), nullable=False),
    sa.Column('txt_reference_type', sa.Enum('ORDER', 'SUBSCRIPTION', 'INVOICE', 'DONATION', 'TOPUP', 'BOOKING', 'FEE', 'ADJUSTMENT', name='enum_reference_type'), nullable=False),
    sa.Column('cod_reference_id', sa.String(), nullable=False),
    sa.Column('int_total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('txt_payment_method', sa.Enum('PIX', 'BANK_SLIP', 'CARD', name='enum_payment_method_type'), nullable=False),
    sa.Column('txt_payment_status', sa.Enum('CREATED', 'PROCESSING', 'PENDING', 'APPROVED', 'FAILED', 'CANCELLED', 'EXPIRED', name='enum_payment_status'), nullable=False),
    sa.Column('txt_items_snapshot', sa.Text(), nullable=True),
    sa.Column('dat_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dat_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cod_payment_id'),
    sa.UniqueConstraint('cod_idempotency_key'),
    sa.UniqueConstraint('cod_payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_payments')
    # ### end Alembic commands ###
