"""create_rest_tables_from_model

Revision ID: d578b23d0dec
Revises: dc0053b40476
Create Date: 2026-03-02 16:16:32.401502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd578b23d0dec'
down_revision: Union[str, Sequence[str], None] = 'dc0053b40476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_payment_boleto',
    sa.Column('cod_payment_boleto', sa.String(), nullable=False),
    sa.Column('cod_boleto_code', sa.Text(), nullable=False),
    sa.Column('cod_boleto_barcode', sa.Text(), nullable=False),
    sa.Column('dat_due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('txt_status_boleto', sa.Enum('CREATED', 'PROCESSING', 'PENDING', 'APPROVED', 'FAILED', 'CANCELLED', 'EXPIRED', name='enum_card_status'), server_default='CREATED', nullable=False),
    sa.Column('dat_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cod_payment_boleto'),
    sa.UniqueConstraint('cod_boleto_barcode'),
    sa.UniqueConstraint('cod_boleto_code'),
    sa.UniqueConstraint('cod_payment_boleto')
    )
    op.create_table('tb_payment_card',
    sa.Column('cod_payment_card', sa.String(), nullable=False),
    sa.Column('txt_card_token', sa.Text(), nullable=False),
    sa.Column('txt_last_numbers', sa.String(), nullable=False),
    sa.Column('txt_card_brand', sa.String(), nullable=False),
    sa.Column('txt_holder_name', sa.String(), nullable=False),
    sa.Column('txt_expiration_month', sa.String(), nullable=False),
    sa.Column('txt_expiration_year', sa.String(), nullable=False),
    sa.Column('txt_status_card', sa.Enum('CREATED', 'PROCESSING', 'PENDING', 'APPROVED', 'FAILED', 'CANCELLED', 'EXPIRED', name='enum_card_status'), server_default='CREATED', nullable=False),
    sa.Column('dat_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cod_payment_card'),
    sa.UniqueConstraint('cod_payment_card')
    )
    op.create_table('tb_payment_pix',
    sa.Column('cod_payment_pix', sa.String(), nullable=False),
    sa.Column('txt_paste_code', sa.Text(), nullable=False),
    sa.Column('dat_expiration_date', sa.String(), nullable=False),
    sa.Column('txt_status_pix', sa.Enum('CREATED', 'PROCESSING', 'PENDING', 'APPROVED', 'FAILED', 'CANCELLED', 'EXPIRED', name='enum_pix_status'), server_default='CREATED', nullable=False),
    sa.Column('dat_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cod_payment_pix'),
    sa.UniqueConstraint('cod_payment_pix'),
    sa.UniqueConstraint('txt_paste_code')
    )
    op.create_table('tb_webhook_events',
    sa.Column('cod_webhook_event', sa.String(), nullable=False),
    sa.Column('txt_provider_name', sa.Enum('STRIPE', 'ABACATE_PAY', 'PAYPAL', 'MOCK', name='enum_provider_transaction_name'), server_default='MOCK', nullable=False),
    sa.Column('cod_provider_event', sa.String(), nullable=False),
    sa.Column('txt_event_type', sa.String(), nullable=False),
    sa.Column('cod_payment_id', sa.String(), nullable=True),
    sa.Column('txt_payload_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dat_received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cod_payment_id'], ['tb_payments.cod_payment_id'], ),
    sa.PrimaryKeyConstraint('cod_webhook_event'),
    sa.UniqueConstraint('cod_webhook_event')
    )
    op.create_unique_constraint(None, 'tb_provider_transactions', ['cod_provider_transaction'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_provider_transactions', type_='unique')
    op.drop_table('tb_webhook_events')
    op.drop_table('tb_payment_pix')
    op.drop_table('tb_payment_card')
    op.drop_table('tb_payment_boleto')
    # ### end Alembic commands ###
