"""create_table_provider_transactions

Revision ID: dc0053b40476
Revises: 68bef59bad4d
Create Date: 2026-02-16 12:42:52.616701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0053b40476'
down_revision: Union[str, Sequence[str], None] = '68bef59bad4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_provider_transactions',
    sa.Column('cod_provider_transaction', sa.String(), nullable=False),
    sa.Column('cod_fk_payment_id', sa.String(), nullable=True),
    sa.Column('txt_provider_name', sa.Enum('STRIPE', 'ABACATE_PAY', 'PAYPAL', 'MOCK', name='enum_provider_transaction_name'), nullable=False),
    sa.Column('cod_provider_id', sa.String(), nullable=False),
    sa.Column('txt_provider_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'EXPIRED', 'REQUIRES_ACTION', name='enum_provider_transaction_status'), server_default='PENDING', nullable=False),
    sa.Column('txt_error_code', sa.String(), nullable=True),
    sa.Column('txt_error_message', sa.String(), nullable=True),
    sa.Column('dat_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dat_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cod_fk_payment_id'], ['tb_payments.cod_payment_id'], ),
    sa.PrimaryKeyConstraint('cod_provider_transaction'),
    sa.UniqueConstraint('cod_provider_transaction')
    )
    op.create_unique_constraint(None, 'tb_payments', ['cod_payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_payments', type_='unique')
    op.drop_table('tb_provider_transactions')
    # ### end Alembic commands ###
